export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const FORGOT_PASS_REQUESTED = 'FORGOT_PASS_REQUESTED';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_ERROR = 'FORGOT_PASS_ERROR';

export const REFRESH_TOKEN_REQUESTED = 'REFRESH_TOKEN_REQUESTED';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';

export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

export const PRODUCT_BY_CATEGORY_REQUESTED = 'RODUCT_BY_CATEGORY_REQUESTED';
export const PRODUCT_BY_CATEGORY_SUCCESS = 'PRODUCT_BY_CATEGORY_SUCCESS';
export const PRODUCT_BY_CATEGORY_ERROR = 'PRODUCT_BY_CATEGORY_ERROR';

export const SELECTCOMPONENT_REQUESTED = 'SELECTCOMPONENT_REQUESTED';
export const SELECTCOMPONENT_SUCCESS = 'SELECTCOMPONENT_SUCCESS';
export const SELECTCOMPONENT_ERROR = 'SELECTCOMPONENT_ERROR';

export const PRODUCTS_REQUESTED = 'PRODUCTS_REQUESTED';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';

export const CREATECATEGORY_REQUESTED = 'CREATECATEGORY_REQUESTED';
export const CREATECATEGORY_SUCCESS = 'CREATECATEGORY_SUCCESS';
export const CREATECATEGORY_ERROR = 'CREATECATEGORY_ERROR';

export const CREATE_PRODUCT_REQUESTED = 'CREATE_PRODUCT_REQUESTED';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

export const DELETE_CATEGORY_REQUESTED = 'DELETE_CATEGORY_REQUESTED';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const EDIT_CATEGORY_REQUESTED = 'EDIT_CATEGORY_REQUESTED';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR';

export const DELETE_PRODUCT_REQUESTED = 'DELETE_PRODUCT_REQUESTED';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const EDIT_PRODUCT_REQUESTED = 'EDIT_PRODUCT_REQUESTED';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';