export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const FORGOT_PASS_REQUESTED = 'FORGOT_PASS_REQUESTED';
export const FORGOT_PASS_SUCCESS = 'FORGOT_PASS_SUCCESS';
export const FORGOT_PASS_ERROR = 'FORGOT_PASS_ERROR';

export const CATEGORIES_REQUESTED = 'CATEGORIES_REQUESTED';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

export const PRODUCT_BY_CATEGORY_REQUESTED = 'RODUCT_BY_CATEGORY_REQUESTED';
export const PRODUCT_BY_CATEGORY_SUCCESS = 'PRODUCT_BY_CATEGORY_SUCCESS';
export const PRODUCT_BY_CATEGORY_ERROR = 'PRODUCT_BY_CATEGORY_ERROR';